name: Test CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [15]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Cache node_modules 📦
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies 👨🏻‍💻
        run: npm ci

      - name: Run linter 👀
        run: npm run lint

      - name: Run Unit Tests 🧪
        run: npm run test

      - name: Generate ⚙️
        run: npm run generate

